### ISSUE TITLE
An idea for improvement.

### ISSUE THREAD

**Issue by carlos-mora** [beckenrode/mysql-workbench-export-laravel-5-migrations#1]
It would benice if the fields added by $table->timestamps() (created_at, updated_at) are recognized and generated as such instead of the regular field declaration

**Comment by beckenrode** [comment]
That's on my list of TODOs, thanks!

**Comment by j0nny55555** [comment]
I found this, might help for working with timestamps in the future (also, I am brand new to Laravel and found your project, thank you for making this!!!)

http://laravel.io/forum/04-17-2014-schema-default-for-date-now

**Comment by beckenrode** [comment]
I've added timestamps, nullabletimestamps, and softdeletes to the latest release.  Thanks!
