### ISSUE TITLE
error calling Python module function GenerateLaravel5Migration.generateLaravel5Migration

### ISSUE THREAD

**Issue by thinkstylestudio** [beckenrode/mysql-workbench-export-laravel-5-migrations#13]
Hi there I just got the following error window pop up when following these instructions

> - Open a model in MySQL Workbench
> - Tools > Catalog > Export Laravel 5 Migration

error calling Python module function GenerateLaravel5Migration.generateLaravel5Migration

let me know what else i can post to help figure out why this isn't working

**Comment by beckenrode** [comment]
I would suggest reinstalling it to see if that solves your issue.
