### ISSUE TITLE
Getting error when executing plugin...

### ISSUE THREAD

**Issue by morales2k** [beckenrode/mysql-workbench-export-laravel-5-migrations#14]
Hi!  I am trying out your plugin on a windows 10 pc. Running latest workbench version, I am getting:

> ### Error during "Export Laravel 5 Migration"
> 
> error calling Python module function
> GenerateLaravel5Migration.generateLaravel5Migration

Not sure what other info I can give to help debug it.... ?

**Comment by VeeeneX** [comment]
It's similar to #7 or #13

**Comment by morales2k** [comment]
Thanks for pointing that out. I will revise my schema to see if I have something not covered in the typesDict.

## Update

Confirmed. This was an error in my schema. Apparently some varchar columns got messed up and were identified only with `(255)` so no correct data-type at all there.... The error message totally misled me into thinking it was the plugin that was at fault. It would be nice if the error messages said something more useful or user-friendly to tackle when the plugin fails because of an error in the schema... So it doesn't look like the plugin is having the error because the plugin is at fault - because the plugin errors out due to faulty schemata in the first place, so it isn't plugin's fault... Probably good if we could see that reflected in the error msg somehow. Just a suggestion there... 

Anyhow, thanks a lot for sharing this plugin! 🎉
