### ISSUE TITLE
No menu item on Ubuntu 14.04

### ISSUE THREAD

**Issue by JonoB** [beckenrode/mysql-workbench-export-laravel-5-migrations#16]
I've installed the plugin (and it shows as enabled in Scripting -> Plugin Manager), but there is no `Catalog` menu option under `Tools`.

I've restarted Workbench several times, and rebooted my computer.

Linux Ubuntu 14.04 and Workbench 6.2

**Comment by VeeeneX** [comment]
I'm using ubuntu too, but 16.04 LTS maybe upgrade Workbench to 6.3? But before doing so purge existing instalation

**Comment by JonoB** [comment]
Workbench 6.3 cannot be installed on Ubuntu 14.04

**Comment by VeeeneX** [comment]
So try reinstalling

**Comment by perseon** [comment]
just installed Workbench 6.3 for this plugin in Ubuntu 16.04, no menu either.

**Comment by VeeeneX** [comment]
Please show us the log, Help > Show Log File

**Comment by VeeeneX** [comment]
@madonion @JonoB Are you sure you have opened Model first?

**Comment by JonoB** [comment]
OK, that makes sense now. I didn't know what `Model` meant.

For anyone else coming to this - if you have an existing DB, then you first need to reverse engineer it using Workbench. You can do this by clicking on the `Database` menu item, and then selecting `Reverse Engineer`. Follow the prompts, and this will create a workbench `Model` for you.

Once you are in the `Model` view, you should then have a `Tools` -> `Catalog` menu item

**Comment by JonoB** [comment]
Thanks for the help @VeeeneX !

**Comment by VeeeneX** [comment]
@JonoB I'm glad to help ;)
