### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by yasinkocak** [beckenrode/mysql-workbench-export-laravel-5-migrations#19]
Great plugin, is there options to make a versioning and migration. If you have changed your database design?

**Comment by VeeeneX** [comment]
Well, currently only updating works, adding new tables with dependencies causes a problem, but could be fixed. Versioning is more complicated I can't find history of changes in workbench, so plugin would need to read all migrations and compare it to database which is a time demanding job. At this point it's hard to achieve

**Comment by yasinkocak** [comment]
I understand it, do you know maybe which application make history of changes like sequel pro or others?

**Comment by VeeeneX** [comment]
@yasinkocak I really don't know :/
