### ISSUE TITLE
Table Inserts?

### ISSUE THREAD

**Issue by samuelpatro** [beckenrode/mysql-workbench-export-laravel-5-migrations#24]
Hey, 
in workbench you can predefine what can be inserted, is uselful for tables where are static info like countries, units, genders,... etc

Its a way to export them to migration?

**Comment by pedrosoares** [comment]
I fork this project and generate another one that does exactly what you want.
https://github.com/pedrosoares/mysql-workbench-export-laravel-5-seeders
If is a wish of the owner of this repo, feel free to join to the project in one single plugin.

**Comment by VeeeneX** [comment]
@pedrosoares Can you open pull request?
