### ISSUE TITLE
Working with Laragon (and MariaDB)

### ISSUE THREAD

**Issue by ivansammartino** [beckenrode/mysql-workbench-export-laravel-5-migrations#25]
Hi,
I'm using [Laragon](https://laragon.org/) for local development, which is shipped with MariaDB instead of MySQL.
MySQL Benchmark is warning me about "incompatible/nonstandard server version or connection protocol detected" (see attachments), but I want to try anyway.
The connection is successful and I can install the plugin, but I don't see the "Catalog" submenu under "Tools"...
Is this a MySQL Benchmark issue or a plugin one? Can this be fixed somehow?
Thank you :-)

![2016-12-22_10-59-16](https://cloud.githubusercontent.com/assets/835377/21421950/c274ec46-c835-11e6-876e-22898d92d0a4.jpg)

![2](https://cloud.githubusercontent.com/assets/835377/21422068/43468794-c836-11e6-8594-75b1256cbed3.jpg)

![3](https://cloud.githubusercontent.com/assets/835377/21422073/46c4f108-c836-11e6-9d9c-d3daad184748.jpg)

**Comment by VeeeneX** [comment]
If you open your Model, do you see Catalog in Tools menu? If not, post your log file with Help > Show Log File

**Comment by ivansammartino** [comment]
Ehr... How do I open my Model?

**Comment by VeeeneX** [comment]
Under connection you have models, you can generate migrations only from models

**Comment by ivansammartino** [comment]
Great, I generated Models from existing Database (Database > Reverse Engineer...) and now I can see the Tools > Catalog > Export Laravel 5 Migration!
I also see that it exports Migrations for all my tables: can I select which table(s) to export?

**Comment by VeeeneX** [comment]
Well this feature isn't supported yet, but I can be you can create issue for this :)

**Comment by ivansammartino** [comment]
Thanks a lot, and sorry for wasting your time: I should have read before the "Open a model in MySQL Workbench" line in README file, it's all clear now! :-)

**Comment by VeeeneX** [comment]
It's fine, I'm glad it works now :)
