### ISSUE TITLE
Remember token column not recognized

### ISSUE THREAD

**Issue by mitto98** [beckenrode/mysql-workbench-export-laravel-5-migrations#30]
I've found a bug at row 301, i've fixed it in a local version 

if col.name == 'remember_token' and typesDict[col_type] == 'string' and str(col.length) == 100:
if col.name == 'remember_token' and typesDict[col_type] == 'string' and str(col.length) == '100':

**Comment by VeeeneX** [comment]
Can you make PR please? It would be nice to have you as a contributor! :)

**Comment by VeeeneX** [comment]
@mitto98 Merged closing
