### ISSUE TITLE
Mysqlworkbench 6.3.9 on Mac Sierra - export issues

### ISSUE THREAD

**Issue by chorton** [beckenrode/mysql-workbench-export-laravel-5-migrations#31]
Hi there.  Performing the export laravel 5 migration brings up the export dialog and shows me the review of what it's going to create, but I only get what I've attached in the screenshot.  I don't get any options for where to save the generated migration scripts and it also never saves anything.

Additionally, none of the foreign keys and references, nor indexes, are being included in the generated scripts

![screen shot 2017-02-08 at 4 43 53 pm](https://cloud.githubusercontent.com/assets/513859/22762721/09eebcf6-ee1e-11e6-95fc-8f9d54d61507.png)

**Comment by buzkall** [comment]
I was having the same problem on a mac, and I've made it work modifying the plugin.
I don't know why, but if I set the button_box with a negative margin in "create_ui" function, I can see the button and it works.
It shows without the proper styles, but it works! :)

![padding](https://cloud.githubusercontent.com/assets/5702/23139518/1168f260-f7ad-11e6-97b6-cc97ff2703b9.png)

I've modified line 507 
`button_box.set_padding(-8)
`

**Comment by VeeeneX** [comment]
@buzkall Do you think that we should include this in the master?

**Comment by buzkall** [comment]
I guess not in that way, because it doesn't render ok... but maybe you know how to fix it now that we know that in mac doesn't show with the original padding.

**Comment by glaubersp** [comment]
I've fixed this problem in the PR #42.
Please, review if it works for everyone.
[]s

**Comment by buzkall** [comment]
Yes! 
Now I see the button at the top, thanks!
 
<img width="890" alt="screen shot 2017-03-14 at 10 19 01" src="https://cloud.githubusercontent.com/assets/5702/23893819/30c1c002-08a0-11e7-9eb7-136548290b13.png">

**Comment by beckenrode** [comment]
Closing; Fixed in #42
