### ISSUE TITLE
Foreign relations not created correctly

### ISSUE THREAD

**Issue by JonoB** [beckenrode/mysql-workbench-export-laravel-5-migrations#34]
I have a few relationships created where there is no `onUpdate` or `onDelete` action specified in the mysql relationship.

This means that when this workbench creates the migrations, it looks something like this:

```
$table->foreign('order_id', 'product_items_order_id_foreign')
  ->references('id')->on('orders')
  ->onDelete('cascade')
  ->onUpdate(''); // this is the issue
```

And this evaluates to:
```
alter table `product_items`
add constraint product_items_order_id_foreign foreign key (`order_id`)
references `orders` (`id`) 
on delete cascade on update 
```

As you can see, there shouldn't be an `on update` part to the relationship. Alternatively, this can be made `RESTRICT`, as this is what mysql defaults to anyway. So the above migrations can be written as:

```
$table->foreign('order_id', 'product_items_order_id_foreign')
  ->references('id')->on('orders')
  ->onDelete('cascade')
  ->onUpdate('restrict'); // or just leave this out completely
```

**Comment by VeeeneX** [comment]
@JonoB Merged closing :)
