### ISSUE TITLE
Menu Tools > Catalog > Export Laravel 5 Migration not appearing

### ISSUE THREAD

**Issue by surajprgupta** [beckenrode/mysql-workbench-export-laravel-5-migrations#37]
OS: Ubuntu 16.04.2 LTS x86_64 
Python 2.7.12

![image](https://cloud.githubusercontent.com/assets/5558630/23103600/6079ed20-f6e3-11e6-9574-7ccc77b88f6e.png)

![image](https://cloud.githubusercontent.com/assets/5558630/23103604/6e346472-f6e3-11e6-95a5-254ce428a29c.png)

Is there any other dependency?

**Comment by VeeeneX** [comment]
Please post your logs from workbench

**Comment by surajprgupta** [comment]
Here it is,

```
23:38:34 [INF][      WBContext]: Parsing application arguments.
23:38:34 [INF][      WBContext]:     /usr/bin/mysql-workbench-bin
23:38:34 [INF][   WBContext UI]: Initializing workbench context UI with these values:
	base dir: /usr/share/mysql-workbench
	plugin path: /usr/lib/mysql-workbench/plugins
	struct path: /usr/share/mysql-workbench/grt
	module path: /usr/lib/mysql-workbench/modules
	library path: /usr/share/mysql-workbench/libraries
	user data dir: /home/surajgupta/.mysql/workbench
	open at start: 
	open type: 
	run at startup: 
	run type: 
	Force SW rendering: No
	Force OpenGL: No
	quit when done: No
23:38:34 [INF][      WBContext]: WbContext::init
23:38:35 [INF][            WBA]: Looking for extension modules for WBA...
23:38:35 [INF][            WBA]: 0 extension modules found
23:38:35 [WRN][            grt]: /usr/share/mysql-workbench/data/table_templates.xml:21: link 'com.mysql.rdbms.mysql.datatype.timestamp' <object db.SimpleDatatype> key=simpleType could not be resolved
23:38:35 [WRN][            grt]: /usr/share/mysql-workbench/data/table_templates.xml:106: link 'com.mysql.rdbms.mysql.datatype.varchar' <object db.SimpleDatatype> key=simpleType could not be resolved
23:38:35 [WRN][            grt]: /usr/share/mysql-workbench/data/table_templates.xml:229: link 'com.mysql.rdbms.mysql.datatype.int' <object db.SimpleDatatype> key=simpleType could not be resolved
23:38:35 [WRN][            grt]: /home/surajgupta/.mysql/workbench/connections.xml:26: link '5971877d-f6bb-11e6-9a76-2c337af997f1' <object GrtObject> key=owner could not be resolved
23:38:35 [INF][      WBContext]: System info:
 	MySQL Workbench Community (GPL) for Linux/Unix version 6.3.8 CE build 1228 (64 bit)
	Configuration Directory: /home/surajgupta/.mysql/workbench
	Data Directory: /usr/share/mysql-workbench
	Cairo Version: 1.14.6
	OS: Linux 4.4.0-62-generic
	CPU: 4x Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (2500.007MHz) - 7.71GiB RAM
	Distribution: Ubuntu 16.04.2 LTS

	Fips mode enabled: no

23:38:37 [INF][      SqlEditor]: Opened connection 'Local instance 3306' to (Ubuntu) version 5.7.17-0ubuntu0.16.04.1
23:38:37 [INF][     AutoCCache]: Initializing autocompletion cache for Local_instance_3306
```

**Comment by DevinNorgarb** [comment]
Same issue, just restarted MySQL Workbench. Appeared immediately.
I'm using Ubuntu 16.04
And thanks for the awesome plugin it just made my day! @beckenrode

**Comment by surajprgupta** [comment]
But for me it isn't, I have restarted workbench several times, also tried uninstalling the plugin and again installing it, restarted laptop but the menu option isn't appearing for me :(

**Comment by DevinNorgarb** [comment]
@surajprgupta I was hoping it would be that easy. 

Are you sure you are in a Model instance when trying to access tools?
like this:
![screenshot from 2017-02-20 22-10-20](https://cloud.githubusercontent.com/assets/12491966/23140391/f70c2b96-f7b9-11e6-9cbf-b9dd4105f82b.png)
(In the screenshot I'm in local DB instance not the model tab.

**Comment by VeeeneX** [comment]
@surajprgupta As @DevinNorgarb mentioned you have opened connection instead of model
```
23:38:37 [INF][      SqlEditor]: Opened connection 'Local instance 3306' to (Ubuntu) version 5.7.17-0ubuntu0.16.04.1
```
So @surajprgupta is right ;)

**Comment by surajprgupta** [comment]
Yes the option is appearing when I am in model @DevinNorgarb @VeeeneX 
but how can I generate the laravel migration code from there for existing database table, 
sorry for this question but I am not that much familiar with mysql workbench

**Comment by surajprgupta** [comment]
Nevermind I think I found the option, after going to the model, have to go to database -> reverse engineer, and then select the connection and table and go through the option and at the end table schema is imported into the model, and then after selecting the table and going to the Tools -> Catalog -> Export Laravel 5 Migration will do what is required.

thank you for the help @VeeeneX @DevinNorgarb
