### ISSUE TITLE
I Just Created an Issue to Say Thank you :)

### ISSUE THREAD

**Issue by noncent** [beckenrode/mysql-workbench-export-laravel-5-migrations#44]
This is cool piece of code , very effective and time saver... thanks allot man! to take initiative and build such a master peace .. thank you .. keep it up! :) :)

**Comment by muhghazaliakbar** [comment]
donate him :D

**Comment by noncent** [comment]
@muhghazaliakbar : It's **Free Software, Hell Yeah!** 😋
