### ISSUE TITLE
Problem when constraint is executed on an inexisting table

### ISSUE THREAD

**Issue by cdarken** [beckenrode/mysql-workbench-export-laravel-5-migrations#5]
The order in which the migrations are generated does not take into account the dependencies between the tables and sometimes the foreign keys are generated for a table that does not yet exists.

Edit: as a solution, maybe extracting all the constraint generation in a separate migration to be executed after table creation would work better.

**Comment by cdarken** [comment]
Please, can you confirm if the issue was valid or not?

**Comment by mclassic** [comment]
If this is a valid issue, one can disable the foreign key checks & constraints during migration.

In [this section](https://laravel.com/docs/5.3/migrations#foreign-key-constraints) of the Laravel 5.3 docs, it can be done as such:

``` php
Schema::enableForeignKeyConstraints();

Schema::disableForeignKeyConstraints();
```
