### ISSUE TITLE
Adding Support for timestamps and soft deletes. 

### ISSUE THREAD

**Issue by dluxcru** [beckenrode/mysql-workbench-export-laravel-5-migrations#51]
As far as I can tell, there is no support for adding soft-deletes and timestamp columns that Laravel migrations support - it would be nice if a dialog box existed when you ran the script that allowed you to check which tables would receive these, rather than having to edit the migrations manually - just fine when dealing with a small database but tedious when dealing with a larger one that has many tables.

 (Laravel has some more complex options for timestamp functions as well, but the very basic support of `$table->softDeletes();` and `$table->timestamps();` autogeneration would be nice. Wouldn't complain if the timezones option could be implemented as well.)

**Comment by dmi90** [comment]
After checking the code it seems like deleted_at, created_at and updated_at fields are supported and get converted to softDeletes() and timestamps(), at least it worked for me just fine. Checking the commit history reflects the same.

**Comment by beckenrode** [comment]
Closing as this is supported.
