### ISSUE TITLE
Files names not matching file content

### ISSUE THREAD

**Issue by wwwillis** [beckenrode/mysql-workbench-export-laravel-5-migrations#55]
I have just installed the plugin into MySQL WorkBench 6.3 ce and when I try do an export it will export the objects but the filenames will not be match the object inside the file. So TableA's migration will be called 2017_11_30_000012_create_TableB_table.php and TableC's migration might be called 2017_11_30_000012_create_TableF_table.php

**Comment by ikodota** [comment]
I have some confusion.

**Comment by tianxingxia-cn** [comment]
I have same confusion

**Comment by Florent23** [comment]
Hello,

I have the same problem

class CreateLocaBonSortieProduitsTable for the file 2018_01_18_000041_create_loca_devis_avis_table

**Comment by ishigami** [comment]
Hi all. 

For me, when it happens. I close Workbench and open again. Then export the migrations without error.

**Comment by yutarux** [comment]
@ishigami 

Hi Ishigami.
I fixed and pushed it.
Please checkout my branch and try it.

**Comment by ishigami** [comment]
Hi @yutarux I'll check it. Tks a lot.

**Comment by beckenrode** [comment]
Fixed by @yutarux in #58 

Thank you!
