### ISSUE TITLE
Error exporting migration with relations and foreign key

### ISSUE THREAD

**Issue by simar88** [beckenrode/mysql-workbench-export-laravel-5-migrations#62]
Hi everyone,
i'm almost happy wwith this script but everytime i tried to export migrations with relationship i find this error: 
**Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint**
Can you help me?
Thanks in advance,
Simone

**Comment by starptit** [comment]
@simar88 
Change type of your foreign key column to unsignedInteger. E.g:

```
$table->unsignedInteger('user_id');

$table->foreign('user_id', 'fk_follow_users_users1_idx')
                ->references('id')->on('users');
```
