### ISSUE TITLE
'Save to file' button almost invisible on OS X Mojave

### ISSUE THREAD

**Issue by jakecausier** [beckenrode/mysql-workbench-export-laravel-5-migrations#69]
A small issue, not sure if it happens on other versions of OS X, but the button to save the migrations to files is obscured by something or has a height of 1px. Here's a screenshot of it (the white line below the generated code):

![Screenshot 2019-11-01 at 14 55 58](https://user-images.githubusercontent.com/37668780/68033704-236c6880-fcb8-11e9-94f1-aa26a10b017f.png)

The button is still clickable, it's just a bit annoying to hit.

**Comment by hermesalvesbr** [comment]
The same problem with my mac os x catalina. Congratulions for the plugin!!!!
