### ISSUE TITLE
Getting 'error calling Python module'

### ISSUE THREAD

**Issue by benxmy** [beckenrode/mysql-workbench-export-laravel-5-migrations#7]
Hi, 
I just installed the plugin (seemed to install cleanly!), and I'm getting the following error

> Error during "Export Laravel 5 Migration"
> error calling Python module function GenerateLaravel5Migration.generateLaravel5Migration

I've done some digging but can't find any info on what may be causing this - not sure if it's an problem on the plugin side, mysql workbench side, or other. Any hints on this? (note: I'm not very familiar with mysql workbench...)

Thanks!

**Comment by beckenrode** [comment]
I'm not seeing this with the latest version of Workbench. Are you still experiencing the problem?

**Comment by benxmy** [comment]
I am still getting the issue (also on the latest version of workbench) - I saw the comments here: https://github.com/beckenrode/mysql-workbench-export-laravel-5-migrations/pull/8 and I'm going to try to remove all the foreign key references, etc just in case (seems very unlikely that's the problem). Should I have the .py file in a specific directory that I'm not aware of or something like that?

**Comment by beckenrode** [comment]
No, It shouldn't matter where the .py file is located, as long as it is correctly installed.

**Comment by chinthakagodawita** [comment]
I was having this issue as well, it turned out to be a custom type that I'd defined in Workbench not being recognised by the script. Adding it to the `typesDict` variable in the script fixed the issue.

The easiest way to debug the problem is to manually run the `.py` file via Scripting > Run Script File.
