### ISSUE TITLE
Laravel 8 migration version

### ISSUE THREAD

**Issue by nicolasvahidzein** [beckenrode/mysql-workbench-export-laravel-5-migrations#84]
Hello,

thank you once again for a terrific package!!

Is it possible to create the laravel 8 version of this plugin with namespaces? Or can i add it manually?

**Comment by nicolasvahidzein** [comment]
Hello,

I looked at your code and can you please just merge this change for laravel 8 migrations?

```
namespace Database\Migrations;

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
```
instead of:
```
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
```

**Comment by nicolasvahidzein** [comment]
It is on line 99 btw, i don't know how to submit a PR so I apologize.

**Comment by beckenrode** [comment]
Hey! I want you to get the GitHub credit for your work. Please following the instructions at https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request and I'll merge it right in! Thank you for your contributions!

**Comment by nicolasvahidzein** [comment]
I feel quite lost, i don't see how i can add a new branch and I don't understand all the steps. It is completely fine with me if you just integrate it. I do not need the credit to be honest. My contribution is so tiny its no big deal. You have my blessing to take the credit and integrate those changes directly. Once again, thank you for a wonderful plugin you created.

**Comment by nicolasvahidzein** [comment]
Actually shouldn't this be a new plugin called: 

beckenrode/mysql-workbench-export-laravel-8-migrations

this would make more sense i feel. Some people are still using laravel 5 migrations.
