### ISSUE TITLE
Unique ID primary keys are converted into auto increment integer fields

### ISSUE THREAD

**Issue by c64skate** [beckenrode/mysql-workbench-export-laravel-5-migrations#9]
When we try to export char(36) ID columns, they are exported as;

$table->increments('id');

Instead, they should be exported as;

$table->char('id', 36);
...
$table->primary('id');

If not manually corrected, this also causes foreign key failures since CHAR and INT fields cannot be connected.

**Comment by beckenrode** [comment]
I believe the latest release corrects this.
